
[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
lib_archive = no
lib_ldf_mode = deep+
build_flags =
    -std=gnu++14
    -I lib/
    -I lib/edge-impulse-sdk
    -I lib/edge-impulse-sdk/classifier
    -I lib/edge-impulse-sdk/porting
    -I lib/model-parameters
    -I lib/tflite-model
    -D EI_CLASSIFIER_TFLITE_ENABLE_CMSIS_NN=0
    -D EI_CLASSIFIER_TFLITE_ENABLE_ESP_DSP=0
    -D EON_EDGES_PORT_ARDUINO=1

build_src_filter =
    +<../src/>
    +<../lib/edge-impulse-sdk/porting/espressif/>
    +<../lib/tflite-model/>
	+<../lib/edge-impulse-sdk/tensorflow/lite/micro/>
    +<../lib/edge-impulse-sdk/tensorflow/lite/micro/kernels/>
    +<../lib/edge-impulse-sdk/tensorflow/lite/kernels/>
	+<../lib/edge-impulse-sdk/tensorflow/lite/c/>
	+<../lib/edge-impulse-sdk/tensorflow/lite/core/api/>


	
lib_deps = 
	adafruit/Adafruit Unified Sensor@^1.1.15
	adafruit/DHT sensor library@^1.4.6
